bf16: true
compute_accuracy: true
dataset: dataset_20260323150517
dataset_dir: e:\python\conda\RAG\app\..\uploads
do_train: true
eval_steps: 50
evaluation_strategy: steps
finetuning_type: lora
gradient_accumulation_steps: 4
learning_rate: 0.0002
logging_dir: e:\python\conda\RAG\app\..\finetuned_models\runs\qwen3_0.6b_v1
logging_steps: 10
lora_alpha: 16
lora_dropout: 0.1
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_length: 2048
model_name_or_path: Qwen/Qwen2.5-0.5B-Instruct
num_train_epochs: 3.0
optim: adamw_torch
output_dir: e:\python\conda\RAG\app\..\finetuned_models\qwen3_0.6b_v1
overwrite_cache: true
overwrite_output_dir: true
per_device_train_batch_size: 4
plot_loss: true
report_to: tensorboard
save_steps: 500
seed: 42
stage: sft
template: default
val_size: 0.1
warmup_steps: 100
weight_decay: 0.0
